name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./healthcenter/pom.xml
          mvn clean package -f ./isolationcamp/pom.xml
          mvn clean package -f ./deliverycenter/pom.xml
          mvn clean package -f ./citizeninfo/pom.xml
          mvn clean package -f ./testingcenter/pom.xml

      - name: Docker Build and push for Healthcenter
        uses: docker/build-push-action@v4
        with:
          context: ./healthcenter
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/healthcenter:latest
            ghcr.io/${{ github.repository }}/healthcenter:${{ github.ref_name }}
            
      - name: Docker Build and push for Isolationcamp
        uses: docker/build-push-action@v4
        with:
          context: ./isolationcamp
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/isolationcamp:latest
            ghcr.io/${{ github.repository }}/isolationcamp:${{ github.ref_name }}
            
      - name: Docker Build and push for Deliverycenter
        uses: docker/build-push-action@v4
        with:
          context: ./deliverycenter
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/deliverycenter:latest
            ghcr.io/${{ github.repository }}/deliverycenter:${{ github.ref_name }}
            
      - name: Docker Build and push for Citizeninfo
        uses: docker/build-push-action@v4
        with:
          context: ./citizeninfo
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/citizeninfo:latest
            ghcr.io/${{ github.repository }}/citizeninfo:${{ github.ref_name }}
            
      - name: Docker Build and push for Testingcenter
        uses: docker/build-push-action@v4
        with:
          context: ./testingcenter
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/testingcenter:latest
            ghcr.io/${{ github.repository }}/testingcenter:${{ github.ref_name }}
            
