apiVersion: apps/v1
kind: Deployment
metadata:
  name: citizeninfo
  labels:
    app: citizeninfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: citizeninfo
  template:
    metadata:
      labels:
        app: citizeninfo
    spec:
      containers:
        - name: citizeninfo
          image: "username/citizeninfo:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
