apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcenter
  labels:
    app: healthcenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcenter
  template:
    metadata:
      labels:
        app: healthcenter
    spec:
      containers:
        - name: healthcenter
          image: "879772956301.dkr.ecr.ca-central-1.amazonaws.com/user10-healthcenter:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
