---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcenter
  labels:
    app: healthcenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcenter
  template:
    metadata:
      labels:
        app: healthcenter
    spec:
      containers:
        - name: healthcenter
          image: username/healthcenter:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: isolationcamp
  labels:
    app: isolationcamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: isolationcamp
  template:
    metadata:
      labels:
        app: isolationcamp
    spec:
      containers:
        - name: isolationcamp
          image: username/isolationcamp:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliverycenter
  labels:
    app: deliverycenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliverycenter
  template:
    metadata:
      labels:
        app: deliverycenter
    spec:
      containers:
        - name: deliverycenter
          image: username/deliverycenter:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: citizeninfo
  labels:
    app: citizeninfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: citizeninfo
  template:
    metadata:
      labels:
        app: citizeninfo
    spec:
      containers:
        - name: citizeninfo
          image: username/citizeninfo:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: testingcenter
  labels:
    app: testingcenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testingcenter
  template:
    metadata:
      labels:
        app: testingcenter
    spec:
      containers:
        - name: testingcenter
          image: username/testingcenter:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: healthcenter
  labels:
    app: healthcenter
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: healthcenter


---


apiVersion: v1
kind: Service
metadata:
  name: isolationcamp
  labels:
    app: isolationcamp
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: isolationcamp


---


apiVersion: v1
kind: Service
metadata:
  name: deliverycenter
  labels:
    app: deliverycenter
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: deliverycenter


---


apiVersion: v1
kind: Service
metadata:
  name: citizeninfo
  labels:
    app: citizeninfo
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: citizeninfo


---


apiVersion: v1
kind: Service
metadata:
  name: testingcenter
  labels:
    app: testingcenter
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: testingcenter

